"""add component positions

Revision ID: 4cff0761bc09
Revises: 8a489fcb6702
Create Date: 2026-06-06 12:07:46.602427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cff0761bc09'
down_revision: Union[str, Sequence[str], None] = '8a489fcb6702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "components",
        sa.Column(
            "x_position",
            sa.Float(),
            nullable=True
        )
    )

    op.add_column(
        "components",
        sa.Column(
            "y_position",
            sa.Float(),
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
