"""create_architectures_table

Revision ID: 8a489fcb6702
Revises: 
Create Date: 2026-06-04 16:27:26.726721

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a489fcb6702'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architectures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architectures_name'), 'architectures', ['name'], unique=True)
    op.create_table('components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('architecture_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('component_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['architecture_id'], ['architectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_name'), 'components', ['name'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('architecture_id', sa.Uuid(), nullable=False),
    sa.Column('source_component_id', sa.Uuid(), nullable=False),
    sa.Column('target_component_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['architecture_id'], ['architectures.id'], ),
    sa.ForeignKeyConstraint(['source_component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['target_component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    op.drop_index(op.f('ix_components_name'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_architectures_name'), table_name='architectures')
    op.drop_table('architectures')
    # ### end Alembic commands ###
